"""add last_updated to stock cache

Revision ID: 6cfc5b882b7b
Revises: 815ce5f23695
Create Date: 2025-05-07 11:02:13.497515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cfc5b882b7b'
down_revision: Union[str, None] = '815ce5f23695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_cache', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.drop_index('ix_users_sub', table_name='users')
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.create_index('ix_users_sub', 'users', ['uid'], unique=False)
    op.drop_column('stock_cache', 'last_updated')
    # ### end Alembic commands ###
