"""expand stock_cache fields

Revision ID: 8f45b855e4a3
Revises: 42ca125e9338
Create Date: 2025-05-07 08:06:05.369181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f45b855e4a3'
down_revision: Union[str, None] = '42ca125e9338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_cache', sa.Column('name', sa.String(), nullable=True))
    op.add_column('stock_cache', sa.Column('exchange', sa.String(), nullable=True))
    op.add_column('stock_cache', sa.Column('change', sa.Float(), nullable=True))
    op.add_column('stock_cache', sa.Column('percent_change', sa.Float(), nullable=True))
    op.add_column('stock_cache', sa.Column('history', sa.String(), nullable=True))
    op.drop_column('stock_cache', 'change_percent')
    op.add_column('users', sa.Column('uid', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.drop_index('ix_users_sub', table_name='users')
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=False)
    op.drop_column('users', 'sub')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sub', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.create_index('ix_users_sub', 'users', ['sub'], unique=False)
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'uid')
    op.add_column('stock_cache', sa.Column('change_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('stock_cache', 'history')
    op.drop_column('stock_cache', 'percent_change')
    op.drop_column('stock_cache', 'change')
    op.drop_column('stock_cache', 'exchange')
    op.drop_column('stock_cache', 'name')
    # ### end Alembic commands ###
