"""Add metrics to stock cache

Revision ID: c4fa779ab085
Revises: 6cfc5b882b7b
Create Date: 2025-05-07 19:47:10.403374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4fa779ab085'
down_revision: Union[str, None] = '6cfc5b882b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_cache', sa.Column('pe_ratio', sa.Float(), nullable=True))
    op.add_column('stock_cache', sa.Column('market_cap', sa.Float(), nullable=True))
    op.add_column('stock_cache', sa.Column('high_52w', sa.Float(), nullable=True))
    op.add_column('stock_cache', sa.Column('low_52w', sa.Float(), nullable=True))
    op.alter_column('stock_cache', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('stock_cache', 'last_updated')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_cache', sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('stock_cache', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('stock_cache', 'low_52w')
    op.drop_column('stock_cache', 'high_52w')
    op.drop_column('stock_cache', 'market_cap')
    op.drop_column('stock_cache', 'pe_ratio')
    # ### end Alembic commands ###
