name: Refresh Stock Cache

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours UTC
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    environment: production  # Tie this job to your configured environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run refresh script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
          ADMIN_EMAILS: ${{ secrets.ADMIN_EMAILS }}
        run: |
          python backend/refresh_stock_cache.py
